### ISSUE TITLE
No build instructions

### ISSUE THREAD

**Issue by rodneyrod** [abderrahim/telepathy-poison#5]
Tried autoconf and ./configure but all it generated was errors and I couldn't get any further.

**Comment by LuccoJ** [comment]
You should probably specify the errors or it will be hard to help... I could compile it without (many) problems.

**Comment by rodneyrod** [comment]
These are the errors I've been getting:

configure.ac:4: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:5: error: possibly undefined macro: AM_SILENT_RULES
configure.ac:8: error: possibly undefined macro: AM_PROG_VALAC

**Comment by LuccoJ** [comment]
You should run autoreconf before running autoconf.
Try that.

**Comment by abderrahim** [comment]
You should run `autoreconf -i` rather than autoconf, it will call all the necessary auto\* for you.

It would be good to have some instruction though.

**Comment by rodneyrod** [comment]
I was away at work and I was gonna try this when I got home and all the work is already done.

You guys are amazing, keep up the good work.
